FROM tomcat:latest
#ADD EBazaar.war /opt/jboss/wildfly/standalone/deployments/
MAINTAINER Mo Nuaimat "nuaimat2002@yahoo.com"


RUN mkdir -p /var/log/e-bazaar/
COPY e-bazaar.war /usr/local/tomcat/webapps/e-bazaar.war