version: '2'
services:
  web:
    build: .
    container_name: e-bazaar_web
    ports:
     - "18080:8080"
    links:
     - database
  database:
    image: mysql:latest
    container_name: e-bazaar_database
    command: mysqld --user=root --verbose
    volumes:
        - ./otherfiles/ebazaar_data.sql:/docker-entrypoint-initdb.d/ebazaar_data.sql
        - ./otherfiles/mysql_caseinsensitive.cnf:/etc/mysql/conf.d/mysql_caseinsensitive.cnf
    ports:
        - "3306:3306"
    environment:
        MYSQL_DATABASE: "test"
        MYSQL_USER: "test"
        MYSQL_PASSWORD: "test"
        MYSQL_ROOT_PASSWORD: "root"
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"